apiVersion: v1
kind: Service
metadata:
  name: ubuntu
  namespace: venuehalls
  labels:
    app: ubuntu
spec:
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
  type:
    LoadBalancer