apiVersion: v1
kind: Service
metadata:
  name: ui-svc
  namespace: venuehalls
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200