apiVersion: v1
kind: Service
metadata:
  name: ui-svc
  namespace: venuehalls
  labels:
    app: ui
spec:
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200




---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  namespace: vedika
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: shivastunts/vedika-angular-testing-fullcode:v1
        ports:
        - containerPort: 4200