apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: venuehalls
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    role: mongo
