apiVersion: v1
kind: Service
metadata:
  name: service-svc
  namespace: venuehalls
spec:
  type: NodePort
  selector:
    app: service
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8057
      targetPort: 8057
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30009