apiVersion: v1
kind: Service
metadata:
  name: service-svc
  namespace: venuehalls
spec:
  type: LoadBalancer
  selector:
    app: service
  ports:
  - protocol: TCP
    port: 8057
    targetPort: 8057